-- Script to upgrade database used by the Common Data Service
-- FROM version 1.14.x TO version 1.15.x.
-- No database is specified to allow flexible deployment!

-- 1
ALTER TABLE C_SOLUTION_REV
  ADD COLUMN ACCESS_TYPE_CD CHAR(2) NOT NULL DEFAULT 'PR';
-- 2
UPDATE C_SOLUTION_REV REV
  SET ACCESS_TYPE_CD = CASE 
  WHEN (SELECT COUNT(*) FROM C_SOLUTION SOL 
                        WHERE SOL.SOLUTION_ID = REV.SOLUTION_ID AND SOL.ACCESS_TYPE_CD IS NOT NULL) > 0
  THEN (SELECT ACCESS_TYPE_CD FROM C_SOLUTION SOL 
                        WHERE SOL.SOLUTION_ID = REV.SOLUTION_ID)
  ELSE 'PR'
END;
-- 3
ALTER TABLE C_SOLUTION
  DROP COLUMN ACCESS_TYPE_CD;
-- 4
ALTER TABLE C_SOLUTION_REV
  ADD COLUMN VALIDATION_STATUS_CD CHAR(2) NOT NULL DEFAULT 'NV';
-- 5
UPDATE C_SOLUTION_REV REV
  SET VALIDATION_STATUS_CD = CASE 
  WHEN (SELECT COUNT(*) FROM C_SOLUTION SOL 
                        WHERE SOL.SOLUTION_ID = REV.SOLUTION_ID AND SOL.VALIDATION_STATUS_CD IS NOT NULL) > 0
  THEN (SELECT VALIDATION_STATUS_CD FROM C_SOLUTION SOL 
                        WHERE SOL.SOLUTION_ID = REV.SOLUTION_ID)
  ELSE 'NV'
END;                   
-- 6
ALTER TABLE C_SOLUTION
  DROP COLUMN VALIDATION_STATUS_CD;
