CREATE TABLE C_STEP_TYPE (
  TYPE_CD CHAR(2) NOT NULL PRIMARY KEY,
  TYPE_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE C_SUB_SCOPE_TYPE (
  TYPE_CD CHAR(2) NOT NULL PRIMARY KEY,
  TYPE_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE C_STEP_STATUS (
  STATUS_CD CHAR(2) NOT NULL PRIMARY KEY,
  STATUS_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE C_PEER_STATUS (
  STATUS_CD CHAR(2) NOT NULL PRIMARY KEY,
  STATUS_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE C_PEER DROP COLUMN CONTACT2;

ALTER TABLE C_PEER DROP COLUMN TRUST_LEVEL;

ALTER TABLE C_PEER
  ADD COLUMN STATUS_CD CHAR(2) NOT NULL,
  ADD FOREIGN KEY C_PEER_C_PEER_STATUS(STATUS_CD) REFERENCES C_PEER_STATUS (STATUS_CD);
  
ALTER TABLE C_PEER
  ADD COLUMN VALIDATION_STATUS_CD CHAR(2) NOT NULL,
  ADD FOREIGN KEY  C_PEER_C_VALIDATION_STATUS(VALIDATION_STATUS_CD) REFERENCES C_VALIDATION_STATUS (STATUS_CD);

  
ALTER TABLE C_PEER_SUB
  ADD COLUMN SCOPE_TYPE CHAR(2) NOT NULL,
  ADD FOREIGN KEY  C_PEER_SUB_C_SCOPE(SCOPE_TYPE) REFERENCES C_SUB_SCOPE_TYPE (TYPE_CD);
  
ALTER TABLE C_PEER_SUB
  ADD COLUMN PROCESSED_DATE TIMESTAMP;
  
ALTER TABLE C_SOLUTION
  ADD COLUMN ORIGIN VARCHAR(512);
  
  
ALTER TABLE C_PEER MODIFY COLUMN WEB_URL VARCHAR(512); 

ALTER TABLE C_PEER DROP COLUMN IS_ACTIVE;

ALTER TABLE C_SOLUTION_REV
  ADD COLUMN ORIGIN VARCHAR(512);
  
ALTER TABLE C_SOLUTION_REV
  ADD COLUMN SOURCE_ID CHAR(36),
  ADD FOREIGN KEY  C_SOLUTION_REV_C_PEER(SOURCE_ID) REFERENCES C_PEER (PEER_ID);
  
CREATE TABLE C_STEP_RESULT (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  STEP_CD CHAR(2) NOT NULL,
  STATUS_CD CHAR(2) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  TRACKING_ID CHAR(36),
  SOLUTION_ID CHAR(36),
  REVISION_ID CHAR(36),
  ARTIFACT_ID CHAR(36),
  USER_ID CHAR(36),
  RESULT VARCHAR(8192),
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP,
  CONSTRAINT C_STEP_RESULT_C_STEP_CD FOREIGN KEY (STEP_CD) REFERENCES C_STEP_TYPE (TYPE_CD),
  CONSTRAINT C_STEP_RESULT_STATUS_CD FOREIGN KEY (STATUS_CD) REFERENCES C_STEP_STATUS (STATUS_CD),
  CONSTRAINT C_STEP_RESULT_C_SOLUTION FOREIGN KEY (SOLUTION_ID) REFERENCES C_SOLUTION (SOLUTION_ID),
  CONSTRAINT C_STEP_RESULT_C_SOLUTION_REV FOREIGN KEY (REVISION_ID) REFERENCES C_SOLUTION_REV (REVISION_ID),
  CONSTRAINT C_STEP_RESULT_C_ARTIFACT FOREIGN KEY (ARTIFACT_ID) REFERENCES C_ARTIFACT (ARTIFACT_ID),
  CONSTRAINT C_STEP_RESULT_C_USER FOREIGN KEY (USER_ID) REFERENCES C_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO C_ACCESS_TYPE (TYPE_CD, TYPE_NAME) VALUES ('RS', 'Restricted');

INSERT INTO C_TOOLKIT_TYPE (TYPE_CD, TYPE_NAME) VALUES ('PB', 'Probe');

INSERT INTO C_STEP_STATUS (STATUS_CD, STATUS_NAME) VALUES ('FA', 'Failed');
INSERT INTO C_STEP_STATUS (STATUS_CD, STATUS_NAME) VALUES ('ST', 'Started');
INSERT INTO C_STEP_STATUS (STATUS_CD, STATUS_NAME) VALUES ('SU', 'Succeeded');


INSERT INTO C_STEP_TYPE (TYPE_CD, TYPE_NAME) VALUES ('OB', 'Onboarding');
INSERT INTO C_STEP_TYPE (TYPE_CD, TYPE_NAME) VALUES ('VL', 'Validation');

INSERT INTO C_TOOLKIT_TYPE (TYPE_CD, TYPE_NAME) VALUES ('TC', 'Training Client');
INSERT INTO C_TOOLKIT_TYPE (TYPE_CD, TYPE_NAME) VALUES ('BR', 'Data Broker');

INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('AC', 'Active');
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('IN', 'Inactive');
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('PA', 'Pending Active');
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('RM', 'Removed');
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('PR', 'Pending Remove');


INSERT INTO C_SUB_SCOPE_TYPE (TYPE_CD, TYPE_NAME) VALUES ('RF', 'Reference');
INSERT INTO C_SUB_SCOPE_TYPE (TYPE_CD, TYPE_NAME) VALUES ('FL', 'Full');















  

  

  
  







