-- Script to upgrade database used by the Common Data Service
-- FROM version 1.13.x TO version 1.14.x.
-- No database is specified to allow flexible deployment!

-- 1
CREATE TABLE C_PEER_GROUP (
  GROUP_ID INT PRIMARY KEY AUTO_INCREMENT, 
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(512),
  CREATED_DATE TIMESTAMP NOT NULL, 
  MODIFIED_DATE TIMESTAMP NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 2
CREATE TABLE C_SOLUTION_GROUP (
  GROUP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(512),
  CREATED_DATE TIMESTAMP NOT NULL,
  MODIFIED_DATE TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 3
CREATE TABLE C_PEER_GRP_MEM_MAP (
  GROUP_ID INT PRIMARY KEY AUTO_INCREMENT,
  PEER_ID CHAR(36) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  CONSTRAINT C_PEER_GRP_MEM_MAP_C_GROUP FOREIGN KEY (GROUP_ID) REFERENCES C_PEER_GROUP (GROUP_ID),
  CONSTRAINT C_PEER_GRP_MEM_MAP_C_PEER FOREIGN KEY (PEER_ID) REFERENCES C_PEER (PEER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 4
CREATE TABLE C_SOL_GRP_MEM_MAP (
  GROUP_ID INT PRIMARY KEY AUTO_INCREMENT,
  SOLUTION_ID CHAR(36) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  CONSTRAINT C_SOL_GRP_MEM_MAP_C_GROUP FOREIGN KEY (GROUP_ID) REFERENCES C_PEER_GROUP (GROUP_ID),
  CONSTRAINT C_SOL_GRP_MEM_MAP_C_SOLUTION FOREIGN KEY (SOLUTION_ID) REFERENCES C_SOLUTION (SOLUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 5
CREATE TABLE C_PEER_SOL_ACC_MAP (
  PEER_GROUP_ID INT NOT NULL, 
  SOL_GROUP_ID INT NOT NULL, 
  GRANTED_YN CHAR(1) DEFAULT 'N' NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (PEER_GROUP_ID, SOL_GROUP_ID),
  CONSTRAINT C_PEER_SOL_ACCESS_MAP_C_PEER FOREIGN KEY (PEER_GROUP_ID) REFERENCES C_PEER_GROUP (GROUP_ID),
  CONSTRAINT C_PEER_SOL_ACCESS_MAP_C_SOLUTION FOREIGN KEY (SOL_GROUP_ID) REFERENCES C_SOLUTION_GROUP (GROUP_ID)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 6
CREATE TABLE C_PEER_PEER_ACC_MAP (
  PRINCIPAL_GROUP_ID INT NOT NULL, 
  RESOURCE_GROUP_ID INT NOT NULL, 
  CREATED_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (PRINCIPAL_GROUP_ID, RESOURCE_GROUP_ID),
  CONSTRAINT C_PEER_PEER_ACCESS_MAP_C_PRINCIPAL FOREIGN KEY (PRINCIPAL_GROUP_ID) REFERENCES C_PEER_GROUP (GROUP_ID),
  CONSTRAINT C_PEER_PEER_ACCESS_MAP_C_RESOURCE  FOREIGN KEY (RESOURCE_GROUP_ID)  REFERENCES C_PEER_GROUP (GROUP_ID)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
